### ISSUE TITLE
GUI not properly loading

### ISSUE THREAD

**Issue by remil1805** [raretypeoffox/vagonuth-package#2]
The character name, info, level hit/dam and so on is not loading.  I am not sure if it is a game or package issue but thought I would report it. 

![image](https://github.com/user-attachments/assets/7ba60b00-f8ca-4449-872d-accc96a09906)

**Comment by raretypeoffox** [comment]
This is a server side issue. Sometimes GMCP doesn't load properly the first time you connect. Try either reconnecting or quitting and connecting again. This may take a few tries but it should load once GMCP is working.
